### ISSUE TITLE
Código duplicado - arquivo /Views/Shared/Object/Product/_ProductInCard.cshtml

### ISSUE THREAD

**Issue by marianacaramico** [jetebusiness/NEO-Default_Theme#16]
Na linha 69 do arquivo **/Views/Shared/Object/Product/_ProductInCard.cshtml** temos ifs duplicados: https://i.gyazo.com/ec6ff97aa035eadda98f180f65518a81.png

**Comment by fabiojet** [comment]
Mariana, primeiramente obrigado pela contribuição.
Na verdade o código não estava duplicado, porém estava errado de qualquer maneira. No primeiro "if" deve ser verificado múltiplas etiquetas.
Realizamos os devidos ajustes e será liberado na próxima release.
Obrigado.

**Comment by ngeraldo-jet** [comment]
@marianacaramico, fizemos os ajustes e já estão disponíveis na versão [2.71.79](https://github.com/jetebusiness/NEO-Default_Theme/releases/tag/2.71.79).

Vou fechar a issue.
